//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace C2LP.ColdStorageDataHubClient.WRUpload {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IColdChainInterface", Namespace="http://tempuri.org/")]
    public partial class ColdChainServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadRefHistDatasOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadCarHistDatasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ColdChainServer() {
            this.Url = global::C2LP.ColdStorageDataHubClient.Properties.Settings.Default.C2LP_ColdStorageDataHubClient_WRUpload_ColdChainServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadRefHistDatasCompletedEventHandler UploadRefHistDatasCompleted;
        
        /// <remarks/>
        public event UploadCarHistDatasCompletedEventHandler UploadCarHistDatasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IColdChainInterface/UploadRefHistDatas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultModelOfboolean UploadRefHistDatas([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/C2LP.WebService.Model")] Model_NodeHistoryData[] refHDList) {
            object[] results = this.Invoke("UploadRefHistDatas", new object[] {
                        refHDList});
            return ((ResultModelOfboolean)(results[0]));
        }
        
        /// <remarks/>
        public void UploadRefHistDatasAsync(Model_NodeHistoryData[] refHDList) {
            this.UploadRefHistDatasAsync(refHDList, null);
        }
        
        /// <remarks/>
        public void UploadRefHistDatasAsync(Model_NodeHistoryData[] refHDList, object userState) {
            if ((this.UploadRefHistDatasOperationCompleted == null)) {
                this.UploadRefHistDatasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadRefHistDatasOperationCompleted);
            }
            this.InvokeAsync("UploadRefHistDatas", new object[] {
                        refHDList}, this.UploadRefHistDatasOperationCompleted, userState);
        }
        
        private void OnUploadRefHistDatasOperationCompleted(object arg) {
            if ((this.UploadRefHistDatasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadRefHistDatasCompleted(this, new UploadRefHistDatasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IColdChainInterface/UploadCarHistDatas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResultModelOfboolean UploadCarHistDatas([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/C2LP.WebService.Model")] Model_NodeHistoryData[] carHDList) {
            object[] results = this.Invoke("UploadCarHistDatas", new object[] {
                        carHDList});
            return ((ResultModelOfboolean)(results[0]));
        }
        
        /// <remarks/>
        public void UploadCarHistDatasAsync(Model_NodeHistoryData[] carHDList) {
            this.UploadCarHistDatasAsync(carHDList, null);
        }
        
        /// <remarks/>
        public void UploadCarHistDatasAsync(Model_NodeHistoryData[] carHDList, object userState) {
            if ((this.UploadCarHistDatasOperationCompleted == null)) {
                this.UploadCarHistDatasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadCarHistDatasOperationCompleted);
            }
            this.InvokeAsync("UploadCarHistDatas", new object[] {
                        carHDList}, this.UploadCarHistDatasOperationCompleted, userState);
        }
        
        private void OnUploadCarHistDatasOperationCompleted(object arg) {
            if ((this.UploadCarHistDatasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadCarHistDatasCompleted(this, new UploadCarHistDatasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/C2LP.WebService.Model")]
    public partial class Model_NodeHistoryData {
        
        private System.DateTime dataTimek__BackingFieldField;
        
        private decimal datak__BackingFieldField;
        
        private int idk__BackingFieldField;
        
        private Enum_HdAlarm isAlarmk__BackingFieldField;
        
        private int pointIdk__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<DataTime>k__BackingField")]
        public System.DateTime DataTimek__BackingField {
            get {
                return this.dataTimek__BackingFieldField;
            }
            set {
                this.dataTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Data>k__BackingField")]
        public decimal Datak__BackingField {
            get {
                return this.datak__BackingFieldField;
            }
            set {
                this.datak__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Id>k__BackingField")]
        public int Idk__BackingField {
            get {
                return this.idk__BackingFieldField;
            }
            set {
                this.idk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IsAlarm>k__BackingField")]
        public Enum_HdAlarm IsAlarmk__BackingField {
            get {
                return this.isAlarmk__BackingFieldField;
            }
            set {
                this.isAlarmk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<PointId>k__BackingField")]
        public int PointIdk__BackingField {
            get {
                return this.pointIdk__BackingFieldField;
            }
            set {
                this.pointIdk__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/C2LP.WebService.Model.MyEnum")]
    public enum Enum_HdAlarm {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Alarm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/C2LP.WebService.Model")]
    public partial class ResultModelOfboolean {
        
        private int codeField;
        
        private bool codeFieldSpecified;
        
        private bool dataField;
        
        private bool dataFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CodeSpecified {
            get {
                return this.codeFieldSpecified;
            }
            set {
                this.codeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataSpecified {
            get {
                return this.dataFieldSpecified;
            }
            set {
                this.dataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadRefHistDatasCompletedEventHandler(object sender, UploadRefHistDatasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadRefHistDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadRefHistDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultModelOfboolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultModelOfboolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UploadCarHistDatasCompletedEventHandler(object sender, UploadCarHistDatasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadCarHistDatasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadCarHistDatasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultModelOfboolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultModelOfboolean)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591